# Generated by Django 2.2.2 on 2020-11-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20201121_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='apps.Roles', verbose_name='角色'),
        ),
    ]
