# Generated by Django 2.2.2 on 2020-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20201121_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='apps.Roles', verbose_name='角色'),
        ),
    ]
