# Generated by Django 2.2.2 on 2020-11-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20201123_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions_classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': '菜单表', 'verbose_name_plural': '菜单表'},
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='url',
        ),
        migrations.AddField(
            model_name='menus',
            name='pid',
            field=models.IntegerField(blank=True, help_text='为0则是一级菜单,指定id则是指定id的二级菜单', null=True, verbose_name='是否为主菜单'),
        ),
        migrations.AddField(
            model_name='menus',
            name='roles',
            field=models.ForeignKey(blank=True, help_text='菜单属于哪个角色', null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Roles', verbose_name='所属角色'),
        ),
        migrations.AddField(
            model_name='menus',
            name='url',
            field=models.CharField(default=1, max_length=128, unique=True, verbose_name='含正则的URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menus',
            name='title',
            field=models.CharField(max_length=32, verbose_name='菜单名称'),
        ),
    ]
