# Generated by Django 2.2.2 on 2020-11-25 04:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20201124_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='roles',
        ),
        migrations.AddField(
            model_name='menus',
            name='roles',
            field=models.ManyToManyField(help_text='菜单属于哪个角色', to='apps.Roles', verbose_name='所属角色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='apps.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$')], verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='apps.Roles', verbose_name='角色'),
        ),
    ]
