# Generated by Django 2.2.2 on 2020-11-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20201125_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions_classify',
        ),
        migrations.AddField(
            model_name='permissions',
            name='pid',
            field=models.IntegerField(blank=True, help_text='0为权限分类指定ID则属于二级', null=True, verbose_name='是否为分类'),
        ),
    ]
