# Generated by Django 2.2.2 on 2020-11-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20201126_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(choices=[('p', 'p'), ('g', 'g')], max_length=1, verbose_name='p | g')),
                ('v0', models.CharField(max_length=32, verbose_name='⽤户组 | ⽤户')),
                ('v1', models.CharField(max_length=32, verbose_name='PATH | ⽤户组')),
                ('v2', models.CharField(blank=True, max_length=32, null=True, verbose_name='METHOD')),
                ('v3', models.CharField(blank=True, max_length=32, null=True)),
                ('v4', models.CharField(blank=True, max_length=32, null=True)),
                ('v5', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'RESTful权限系统',
                'verbose_name_plural': 'RESTful权限系统',
                'db_table': 'casbin_rule',
            },
        ),
    ]
