# Generated by Django 2.2.2 on 2020-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_casbinrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(help_text='0 为权限组,', verbose_name='类型')),
                ('title', models.CharField(max_length=32, verbose_name='角色/角色组名称')),
            ],
            options={
                'verbose_name': 'casbin角色',
                'verbose_name_plural': 'casbin角色',
                'db_table': 'CasbinRoles',
            },
        ),
        migrations.CreateModel(
            name='CasbinUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色/角色组名称')),
                ('roles', models.ManyToManyField(help_text='绑定角色', to='apps.CasbinRoles', verbose_name='绑定角色')),
            ],
            options={
                'verbose_name': 'casbin用户',
                'verbose_name_plural': 'casbin用户',
                'db_table': 'CasbinUsers',
            },
        ),
        migrations.CreateModel(
            name='CasbinPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限名称')),
                ('ptype', models.CharField(choices=[('p', '角色'), ('g', '角色组')], max_length=1, verbose_name='数据类型p | g')),
                ('url', models.CharField(max_length=128, verbose_name='含正则的URL')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT')], default='GET', max_length=2010, verbose_name='请求方法')),
                ('roles', models.ManyToManyField(help_text='权限归属那个角色或者角色组', to='apps.CasbinRoles', verbose_name='所属角色')),
            ],
            options={
                'verbose_name': 'casbin权限',
                'verbose_name_plural': 'casbin权限',
                'db_table': 'CasbinPermissions',
            },
        ),
    ]
