# Generated by Django 2.2.2 on 2020-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20201129_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casbinpermissions',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='权限归属那个角色或者角色组', to='apps.CasbinRoles', verbose_name='所属角色'),
        ),
        migrations.AlterField(
            model_name='casbinusers',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='绑定角色', to='apps.CasbinRoles', verbose_name='绑定角色'),
        ),
    ]
