# Generated by Django 2.2.2 on 2020-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20201129_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='slug',
            field=models.CharField(max_length=64, verbose_name='标识'),
        ),
    ]
